# Generated by Django 3.2.7 on 2021-10-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maize_api', '0005_alter_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.TextField(),
        ),
    ]
