# Generated by Django 3.2.8 on 2021-10-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maize_api', '0006_alter_data_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='predicted_class',
            new_name='user_id',
        ),
    ]
