# Generated by Django 3.2.8 on 2021-10-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maize_api', '0007_rename_predicted_class_data_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
