# Generated by Django 3.2.8 on 2021-10-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maize_api', '0008_alter_data_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='data',
            name='encoded_image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='predicted_class',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='time_stamp',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='user_id',
            field=models.TextField(),
        ),
    ]
