# Generated by Django 3.2.8 on 2021-10-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maize_api', '0009_auto_20211021_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(height_field=224, null=True, upload_to='uploads/', width_field=224),
        ),
    ]
