# Generated by Django 3.2.8 on 2021-10-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maize_api', '0011_alter_data_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='image',
        ),
        migrations.AddField(
            model_name='data',
            name='image_path',
            field=models.TextField(null=True),
        ),
    ]
