# Generated by Django 3.2.8 on 2021-10-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maize_api', '0012_auto_20211021_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='crop_type',
            field=models.TextField(null=True),
        ),
    ]
