# Generated by Django 3.2.8 on 2021-11-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maize_api', '0016_rename_user_id_data_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_name', models.CharField(default='default_name', max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
