# Generated by Django 3.2.8 on 2021-11-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maize_api', '0020_rename_startlongitude_videoframe_endlongitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoframe',
            name='endLatitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='videoframe',
            name='startLongitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
